### PR TITLE
Add v6p1 2017 data and more MC samples

### PR DESCRIPTION
**Pull request by pieterdavid**
Since the file is getting quite large, I also added a script to check for duplicates, and the travis config for it (I'm not a member of the @cms-top organisation, but it's only a few clicks on travis-ci.org for anyone with the necessary privileges to enable that as a PR check)

### CODE REVIEW

**Comment by swertz** [comment]
Thanks a lot! That will be useful, I've requested travis access to cms-top as I'm not an owner... I don't remember if it will already trigger the CI for this PR or if it needs to be set up before.

Should we split up the file? It would not necessarily help to avoid duplicates anyway...

**Comment by pieterdavid** [comment]
> Thanks a lot! That will be useful, I've requested travis access to cms-top as I'm not an owner... I don't remember if it will already trigger the CI for this PR or if it needs to be set up before.

IIRC it would need some trigger (but there are some tricks for that, like an empty commit)

> Should we split up the file? It would not necessarily help to avoid duplicates anyway...

I also thought about that... we could split data and MC, but I don't think it makes much of a difference (in any case the file is a bit big to scroll, but easy to search and edit; parsing one file is slightly easier than many, but not too significant eitehr).

**Comment by swertz** [comment]
It seems I cannot activate travis although I obtained organization access and I'm admin of this repository... Does one need to be owner to activate it?

Another option would be to use the github workflows...

**Comment by swertz** [comment]
I've managed to activate it (had to sign out & back in to to github & travis and clear cookies...).

Can you try to push to see it if triggers the build?

**Comment by swertz** [comment]
Perfect, thanks again!

**Pull request merged**
