### PR TITLE
2016 and 2018 samples produced by Robert, Enrique, and Barbara

### PR DESCRIPTION
**Pull request by pieterdavid**
I got these as a byproduct from my scripts to transfer and check the samples... it's the automatically generated based on the DAS queries, so please check that I got the right ones before merging.

CC @schoef @epalencia (I couldn't find Barbara on github)

### CODE REVIEW

**Comment by swertz** [comment]
Thanks! Given the caveat I'll wait for a +1 from @schoef and @epalencia before merging this.

**Comment by epalencia** [comment]
For data 2018, the datasets are correct (those are the only datasets valid in DAS with my name). I also took care of other MC samples (as listed [here](https://docs.google.com/spreadsheets/d/1SAtx-eRIuXwLp2WAuUw28no2wdV3dXBkQ8-a6jmYmBk/edit#gid=1985221119) but I believe not all of them appear here. The full list is given [here](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=dataset+dataset%3D%2F*%2Fpalencia-TopNanoAODv6-1-*%2FUSER)

**Comment by swertz** [comment]
> I also took care of other MC samples (as listed here but I believe not all of them appear here. The full list is given here

@epalencia I had already added some of those from the google sheets that were finished at the time (9 of them). Using the YML file from this PR I see only one of yours that is in DAS but not in the YML, that is
```
/ST_tW_top_5f_inclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/palencia-TopNanoAODv6-1-1_2016-88146d75cb10601530484643de5f7795/USER
```
That one has also been produced by @schoef, which is the one listed in @pieterdavid 's YML as:
```
/ST_tW_top_5f_inclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/schoef-TopNanoAODv6-1-1_2016-88146d75cb10601530484643de5f7795/USER
```
However Robert's has 4983500 events (100% of the parent) whereas yours has 3782800, so I'd propose we keep Robert's.

@schoef is the list of datasets included here OK with you?

**Comment by epalencia** [comment]
Hi @swertz , yes, in case of duplicate datasets I believe that taking the one with more stats. is the best way to go. I will invalidate that one so it does not make more confussion. Just to make sure, the one above, is the only dataset I produced not included in the "final" list, no?

**Comment by swertz** [comment]
> Just to make sure, the one above, is the only dataset I produced not included in the "final" list, no?

Yes, that is the case!

**Comment by epalencia** [comment]
> > Just to make sure, the one above, is the only dataset I produced not included in the "final" list, no?
> 
> Yes, that is the case!

Ok, it has been invalidated.

**Pull request merged**
